mt-mods/mail

- gui.lua
I have manually tested this bugfix on EdenLost, using the following mail message data file.  Without the fix, server crashes; with the fix, no crash and the missing json fields (`cc` in this case) are just blank in the GUI.
```
~/EdenLost $ cat mnt/worlds/world/mails/sysadmin.json  | jq
[
{
"body": "body",
"sender": "DO NOT REPLY",
"subject": "subject",
"time": 1642584626.0,
"to": "self",
"unread": false
}
]
```
> Fixes https://github.com/EdenLostMinetest/edenlost/issues/8

- gui.lua
currently, if you delete a message, we forget which message index was selected, so you have to click on another message to delete/read another. previously, you could keep hitting "delete" to remove many messages. this was something i introduced w/ the last PR, i don't remember why or even if it was intentional.
> don't forget which message was selected

- gui.lua
This merge request allows you to see the date and the time while reading the message. It is based on `os.date()` native function which convert the epoch stored in the `.json` into a specific string, here `%Y-%m-%d %X`.
Related to #19
> Show date time

- gui.lua
It was due to an extra statement (`message.subject`). It now works whatever you're in inbox or in message reading formspec.
Related to #13  
Tested with 5.4.1
> Repair forward button in read view

- .luacheckrc
- init.lua
- ui/compose.lua
- ui/contacts.lua
- ui/drafts.lua
- ui/edit_contact.lua
- ui/edit_maillists.lua
- ui/inbox.lua
- ui/maillists.lua
- ui/message.lua
- ui/outbox.lua
- ui/select_contact.lua
@Athozus i took the liberty and moved the translator var into the dependent modules
The `S` variable would leak into the global namespace otherwise (other mods can't really use this anyway)
> declare the translator in every module instead of a global

- ui/message.lua
Fix HUD staying there even you had read the message
Definitely closes #45
> Fix permanent HUD

- storage.lua
- ui/events.lua
- ui/inbox.lua
- ui/outbox.lua
Be aware that this PR is targeting message-sorting branch, not master branch.
Decided to make changes in separate branch to make it easier to see what would be changed.
@Athozus 
Reworks `mail.sort_messages(...)` function to decouple it from user interface handles / formspec fields.
Function was used like this:
```lua
-- second argument sorting field, last argument is sort direction (both are formspec dropdown indexes)
local sortedmessages = mail.sort_messages(messages, "2", "2")
```
And after changes done here it will be used like this:
```lua
-- second argument sorting field, last argument is sort direction (ascending if true)
local sortedmessages = mail.sort_messages(messages, "subject", true)
```
> Rework mail.sort_messages

- chatcommands.lua
- init.lua
- storage.lua
- ui/events.lua
- ui/inbox.lua
- ui/outbox.lua
* Overall LoC +105 −165 (which already includes few unrelated additions)
* Makes filtering safe (deliberate invalid Lua pattern to crash server)
* Makes filtering and sorting happen on demand, wont filter or sort if results wont be actually used.
* Makes sorting function more readable and utilizes in place sorting.
~~Be aware that this is incomplete work.~~
~~There's 2 operation modes for `sortfield == "1"`, this is because I was not sure how exactly it is supposed to work.~~ Fixed.
~~Maybe it is supposed to be like `a.from < b.from or a.to < b.to `?~~ Fixed.
This will also modify original table but I think that shouldn't be problem, not 100% sure though... Checked this too, now makes shallow copy.
> Simplify sorting and make it more readable

- ui/events.lua
If you had some items selected in `outbox` and then you clicked on selected all, you got an oversized number (ex 235 instead of 122 messages), because of an `inbox` instead of `sent` in the `selected_idxs`.
This is a trivial issue, so I merge directly.
> Fix oversized selected number

- storage.lua
- ui/events.lua
Reduce significantly time of action on several messages
It calls only one time for each action (eg. mark read) the entry, instead of one for each messages. So, it passes from 200 calls to only 1. For ex, it reduces execution time from 20 seconds to less than 0.5.
> Fix lag with multiple selection action

- ui/events.lua
when you push the read button without selecting a mail first the mail mod crashes the full server. This pull request is supposed to fix that.
> crash fixes

- storage.lua
fixes crashes in #97 but multiple selections might still not work
> partial fox for #97

- storage.lua
see discussion in #97 and #98 (the `break` just breaks out of the _inner_ loop, the messages still get iterated over)
for example this player-entry here:
```lua
local entry = {
inbox = {
{ id = "a" },
{ id = "b" },
{ id = "c" }
}
}
```
and if you want to delete messages with the following msg_id's:
```lua
msg_ids = { "c", "b" }
```
The mail with id `c` will get matched first and removed, after that the inbox looks like this:
```lua
inbox = {
{ id = "a" },
{ id = "b" }
}
```
But the inner loop still continues with the exact same `i` value and tries to dereference `inbox[3]` (which it does not find)
The break ensures that the `i` iterator value is actually sane and does point to a valid entry.
> fix `mail.delete_mail` (again)

- init.lua
- storage.lua
- ui/settings.lua
This PR contains all from the new settings management. Let's explain a bit how it works :
- `init.lua` : here you defines the settings
- `mail.settings` : the whole list of settings with `setting = { -- data }` structure
- `mail.settings_groups` : the list of groups of settings (for settings page)
- then it generates `selected_idxs` sub-tables for each settings
- `settings.lua` : the redesigned ui page
- first of all, it defines a base of `x` and `y` values
- after that, it creates a temporary table for ordering settings depending on their `index` value (for the selected group)
- then it iterates through the settings and generate UI for each type of settings
- when the player sends fields, it saves in `selected_idxs` the temporary value
Info for settings definition :
- required : `type` …
> Reworked settings

- ui/message.lua
checks if the message to display is non-nil and skips the formspec part if it is nil
the cause of the `nil` messages could be some race-condition in the show/callback logic of the formspecs, until this is proven and can be reproduced this will fix #115 and any other nil-message related crash
> check if message is found in `mail.show_message`

- init.lua
- onjoin.lua
- ui/about.lua
- ui/contacts.lua
- ui/drafts.lua
- ui/inbox.lua
- ui/maillists.lua
- ui/message.lua
- ui/outbox.lua
- ui/receivers.lua
- ui/select_contact.lua
- ui/settings.lua
- ui/trash.lua
- util/colors.lua
- util/init.lua
This is a rework of mail colors. It is a prerequisite for #102, as the addition of it will add many colors. So, it has the following changes : 
- Remove colors from `init.lua`
- Add an utility file `/util/colors.lua`
- Only one global function `mail.get_color()` which returns a color from mixed base colors. It overpasses the mix if there is only one color given.
- Local function `get_base_color()`. The inheritor of `init.lua`. It uses shortcuts of one letter to be simplified and notably for the use of `mail.get_color()`. Of course, comments to tell what is what.
- Local functions to convert from hex to rgb and vice-versa.
- Local function to mix rgb colors.
- EDIT : and, of course, it replaces all the previous occurrences of `mail.colors`
An example of use : 
- Old : …
> Add colors utilities

- ui/message.lua
As suggested in #120 by @nonfreegithub, I made a small script to generate interleaved style by putting `>` chars before each new line.
I'm making a pull request in case some features/details are requested, notably for formspec visualization, even if it's hard, if it's a well-demanded feature, then I can work on it.
Note that it uses a local function `interleaveMsg()`, because the code is shared for both replying (all)/forwarding.
I let you a screenshot anyway.
> Use interleaved style

- storage.lua
fixes synchronization issues if other applications write directly to the mail-entries in the mod-storage
> evict cached storage entries periodically

- ui/compose.lua
- ui/edit_maillists.lua
This is my fix for the bugs. I tested that the bugs were fixed by this, but I didn't run designed tests for the mod.
> fix for bugs #135 and #136

- api.lua
- api.md
- api.spec.lua
- init.lua
- player_recipients.lua
- util/normalize.lua
- util/normalize.spec.lua
This PR allows sending mail to non-player recipients.
There are some potential usecases for this PR:
* Interaction with automated systems (e.g. remote control)
* Mailing lists; in particular, it could allow (for example) sending messages to all members of a beerchat channel, which can be useful for (for public channels) announcements or (for private channels) internal communication without having to keep track of the members.
Checklist:
- The sender should not receive mail addressed to a list if the sender is not otherwise listed as a recipient.
- The sender may send mail to an alias (and should also receive it)
(I hope I did not miss anything important.)
<details><summary>Advtrains</summary>
<p>
For people into Advtrains, I put together a simple patch for Advtrains as a proof-of-concept …
> Implement non-player recipients

- api.lua
- api.spec.lua
- storage.lua
Fixes #138.
Also addresses https://github.com/mt-mods/mail/issues/138#issuecomment-2004769746 by not allowing players to send the mail if there is no valid recipient.
> Cleanly handle player mailling lists

- ui/about.lua
*Note: this is a proposed addition to #141, which is why this PR uses `improved-options-ui` as the based branch instead of `master`.*
This preserves the current mode as the default where the contributor list is displayed as `| Name | Contribution |`, but adds a new mode that shows contributors as a list grouped by the type of contribution (see screenshot)
---
On a less related note, IMO the formspecs should be modified to use real coordinates in the future.
> Implement grouping by contribution type

- ui/about.lua
- ui/settings.lua
This pull request does :
* adjust settings layout [figure 1]
* adjust about layout [figure 2]
* improve contributors list by displaying codes (will become soon icons, when we'll find a pixel artist) + updated list [figure 2]
* GH/CDB buttons send their url in the chat to be Ctrl+clicked
It is not really essential but it gives more space for settings, as I will increase soon the number of settings.
> Adjusted options UI

- migrate.lua
- util/uuid.lua
This is a proposal for the most important hotfix of this release. What does it do ?
* It first checks, when giving an UUID, if it is not already used in the database ;
* At the startup, in after migrating in `migrate.lua`, it checks for non-duplicates, and if there are, it gives new ID to all messages that are not the same (`mail.are_message_sames()`). Of course, because it iterates through all messages, after fixing message1, it checks message2, so if there is a message3 also concerned by the duplicate, it is fixed in the message2 loop.
I tested it with 10 000 messages, it runs quite good (no performance loss). If you want to test it, you can use the `/mail_spam` command written in #103.
Of course, performance can still be improved, but that's not really a mess here.
I ping @Bastrabun …
> Repair UUIDs duplicates (storage 3.1 upgrade)

- .luacheckrc
- ui/settings.lua
- util/settings.lua
Hi,
This is not a big change, but it might be used in the future.
There are two commits, I prefer non-squash for this one : 
* Add a support for parent settings, in `ui/settings.lua` it generates it with a recursive function (not so bad because it is not intended to get thousands of categories)
* Move existing `Default sorting field/direction` to new group `Fields`, child of `Message list`
NB : I'm gonna do a new fields-related setting, so of course this was in my "roadmap" (not famous for being linear lol)
NB2 : I plan to move settings and other non-mail related stuff to new general mods.
> Add support for tree-hierarchized settings groups

- ui/message.lua
- ui/settings.lua
- util/settings.lua
This PR has 2 commits : 
* Add support for setting type `number`. Almost like `string`.
* Add `timezone_offset` setting, and add it to the message date.
Rebase should be the best option.
Quite simple, the review should be quick :wink:
Resolve #125
> Add Timezone offset setting + setting type number

- ui/inbox.lua
Moves the `mail.get_setting(name, "mute_list")` call out of the message loop. Previously, this is repeated, causing disastrous lag when using mail with beerchat.
This PR is ready for review.
[Profiler report before the change](https://github.com/user-attachments/assets/b90ad64d-2031-430c-9c85-5c3a4c75276a)
[Profiler report after the change](https://github.com/user-attachments/assets/abf402b2-3aa1-40dd-a5a3-880dd934c139)
> Optimize performance of the inbox

- migrate.lua
Fix #152 
@MoNTE48 can you confirm me that it works ?
Notes :
- It checks if `get_keys()` exists
- Then, if not, it iterates through existing players (but consume more)
- I've also reorganized into more functions to not have too much duplicates
> Add support for a get_keys() equivalent for lower than 5.7 Minetest versions
